// Package genrust emits the Rust side of a deez-nats contract: prost-annotated
// message structs / enums (byte-compatible with Go's protobuf wire), subjects,
// typed async clients + server traits (RPC), and event publisher/subscriber
// helpers, plus a once-emitted `dnats` runtime reproducing the deez-nats
// envelope on top of prost + async-nats.
package genrust

import (
	"bytes"
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/leinodev/deez-nats/dnatsgen/internal/model"
)

//go:embed templates/api.rs.tmpl templates/dnats.rs
var templatesFS embed.FS

var apiTmpl = template.Must(template.New("api.rs.tmpl").
	Funcs(template.FuncMap{
		"snake":      snake,
		"upperSnake": func(s string) string { return strings.ToUpper(snake(s)) },
	}).
	ParseFS(templatesFS, "templates/api.rs.tmpl"))

// GenerateContract emits <stem>.rs (messages + NATS glue) for one contract.
func GenerateContract(fd protoreflect.FileDescriptor, c *model.Contract, stem, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by dnatsgen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// source: %s\n", stem)
	b.WriteString("#![allow(clippy::all, dead_code, unused_imports)]\n\n")
	b.WriteString("use crate::dnats::{self, DnatsError};\n\n")
	writeExternalTypeImports(&b, fd)

	b.WriteString("// ==== messages ====\n\n")
	writeMessages(&b, fd)

	var api bytes.Buffer
	if err := apiTmpl.Execute(&api, c); err != nil {
		return fmt.Errorf("render api.rs: %w", err)
	}
	b.WriteString(api.String())

	return os.WriteFile(filepath.Join(outDir, stem+".rs"), []byte(b.String()), 0o644)
}

// GenerateRuntime emits dnats.rs into outDir (emit once per Rust crate).
func GenerateRuntime(outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	data, err := templatesFS.ReadFile("templates/dnats.rs")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(outDir, "dnats.rs"), data, 0o644)
}

// ---- message emission (prost) ----

// writeExternalTypeImports imports protobuf types referenced from another
// generated Rust module. Message emission intentionally flattens nested types,
// so the imported identifiers follow the same convention.
func writeExternalTypeImports(b *strings.Builder, fd protoreflect.FileDescriptor) {
	refs := make(map[string]map[string]struct{})

	var messages []protoreflect.MessageDescriptor
	var enums []protoreflect.EnumDescriptor
	collect(fd.Messages(), fd.Enums(), &messages, &enums)
	for _, message := range messages {
		fields := message.Fields()
		for i := 0; i < fields.Len(); i++ {
			field := fields.Get(i)
			if field.IsMap() {
				addExternalFieldType(refs, fd, field.MapValue())
				continue
			}
			addExternalFieldType(refs, fd, field)
		}
	}

	modules := make([]string, 0, len(refs))
	for module := range refs {
		modules = append(modules, module)
	}
	sort.Strings(modules)
	for _, module := range modules {
		names := make([]string, 0, len(refs[module]))
		for name := range refs[module] {
			names = append(names, name)
		}
		sort.Strings(names)
		fmt.Fprintf(b, "use crate::%s::{%s};\n", module, strings.Join(names, ", "))
	}
	if len(modules) > 0 {
		b.WriteString("\n")
	}
}

func addExternalFieldType(refs map[string]map[string]struct{}, current protoreflect.FileDescriptor, field protoreflect.FieldDescriptor) {
	var descriptor protoreflect.Descriptor
	switch field.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		descriptor = field.Message()
	case protoreflect.EnumKind:
		descriptor = field.Enum()
	default:
		return
	}

	parent := descriptor.ParentFile()
	if parent.Path() == current.Path() {
		return
	}
	module := snake(strings.TrimSuffix(filepath.Base(parent.Path()), filepath.Ext(parent.Path())))
	if refs[module] == nil {
		refs[module] = make(map[string]struct{})
	}
	refs[module][string(descriptor.Name())] = struct{}{}
}

func writeMessages(b *strings.Builder, fd protoreflect.FileDescriptor) {
	var msgs []protoreflect.MessageDescriptor
	var enums []protoreflect.EnumDescriptor
	collect(fd.Messages(), fd.Enums(), &msgs, &enums)

	for _, ed := range enums {
		writeEnum(b, ed)
	}
	for _, md := range msgs {
		writeMessage(b, md)
	}
}

// collect flattens all non-map-entry messages and enums (nested included).
func collect(msgs protoreflect.MessageDescriptors, enums protoreflect.EnumDescriptors, outMsgs *[]protoreflect.MessageDescriptor, outEnums *[]protoreflect.EnumDescriptor) {
	for i := 0; i < enums.Len(); i++ {
		*outEnums = append(*outEnums, enums.Get(i))
	}
	for i := 0; i < msgs.Len(); i++ {
		md := msgs.Get(i)
		if md.IsMapEntry() {
			continue
		}
		*outMsgs = append(*outMsgs, md)
		collect(md.Messages(), md.Enums(), outMsgs, outEnums)
	}
}

func writeEnum(b *strings.Builder, ed protoreflect.EnumDescriptor) {
	b.WriteString("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, ::prost::Enumeration)]\n")
	b.WriteString("#[repr(i32)]\n")
	fmt.Fprintf(b, "pub enum %s {\n", ed.Name())
	vals := ed.Values()
	for i := 0; i < vals.Len(); i++ {
		v := vals.Get(i)
		fmt.Fprintf(b, "    %s = %d,\n", enumVariant(string(ed.Name()), string(v.Name())), v.Number())
	}
	b.WriteString("}\n\n")
}

func writeMessage(b *strings.Builder, md protoreflect.MessageDescriptor) {
	b.WriteString("#[derive(Clone, PartialEq, ::prost::Message)]\n")
	fields := md.Fields()
	if fields.Len() == 0 {
		fmt.Fprintf(b, "pub struct %s {}\n\n", md.Name())
		return
	}
	fmt.Fprintf(b, "pub struct %s {\n", md.Name())
	for i := 0; i < fields.Len(); i++ {
		attr, name, typ := rustField(fields.Get(i))
		fmt.Fprintf(b, "    %s\n    pub %s: %s,\n", attr, name, typ)
	}
	b.WriteString("}\n\n")
}

// rustField returns the prost attribute, Rust field name, and Rust type.
func rustField(fd protoreflect.FieldDescriptor) (attr, name, typ string) {
	name = rustIdent(string(fd.Name()))
	tag := fmt.Sprintf("tag = \"%d\"", fd.Number())

	switch {
	case fd.IsMap():
		kKw, kTy := prostScalar(fd.MapKey())
		vKw, vTy := prostElem(fd.MapValue())
		attr = fmt.Sprintf("#[prost(map = \"%s, %s\", %s)]", kKw, vKw, tag)
		typ = fmt.Sprintf("::std::collections::HashMap<%s, %s>", kTy, vTy)
		return
	case fd.IsList():
		kw, ty := prostElem(fd)
		attr = fmt.Sprintf("#[prost(%s, repeated, %s)]", kw, tag)
		typ = fmt.Sprintf("::prost::alloc::vec::Vec<%s>", ty)
		return
	}

	switch fd.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		attr = fmt.Sprintf("#[prost(message, optional, %s)]", tag)
		typ = fmt.Sprintf("::core::option::Option<%s>", fd.Message().Name())
	case protoreflect.EnumKind:
		attr = fmt.Sprintf("#[prost(enumeration = \"%s\", %s)]", fd.Enum().Name(), tag)
		typ = "i32"
	default:
		kw, ty := prostScalar(fd)
		attr = fmt.Sprintf("#[prost(%s, %s)]", kw, tag)
		typ = ty
	}
	return
}

// prostElem is prostScalar plus the message/enum cases (for repeated / map values).
func prostElem(fd protoreflect.FieldDescriptor) (kw, ty string) {
	switch fd.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return "message", string(fd.Message().Name())
	case protoreflect.EnumKind:
		return fmt.Sprintf("enumeration(%s)", fd.Enum().Name()), "i32"
	default:
		return prostScalar(fd)
	}
}

// prostScalar maps a scalar proto kind to (prost keyword, Rust type). The keyword
// selects the wire encoding (zigzag / fixed) so the Rust type stays plain.
func prostScalar(fd protoreflect.FieldDescriptor) (kw, ty string) {
	switch fd.Kind() {
	case protoreflect.StringKind:
		return "string", "::prost::alloc::string::String"
	case protoreflect.BoolKind:
		return "bool", "bool"
	case protoreflect.BytesKind:
		return "bytes = \"vec\"", "::prost::alloc::vec::Vec<u8>"
	case protoreflect.Int32Kind:
		return "int32", "i32"
	case protoreflect.Sint32Kind:
		return "sint32", "i32"
	case protoreflect.Sfixed32Kind:
		return "sfixed32", "i32"
	case protoreflect.Uint32Kind:
		return "uint32", "u32"
	case protoreflect.Fixed32Kind:
		return "fixed32", "u32"
	case protoreflect.Int64Kind:
		return "int64", "i64"
	case protoreflect.Sint64Kind:
		return "sint64", "i64"
	case protoreflect.Sfixed64Kind:
		return "sfixed64", "i64"
	case protoreflect.Uint64Kind:
		return "uint64", "u64"
	case protoreflect.Fixed64Kind:
		return "fixed64", "u64"
	case protoreflect.FloatKind:
		return "float", "f32"
	case protoreflect.DoubleKind:
		return "double", "f64"
	default:
		return "string", "::prost::alloc::string::String"
	}
}

// ---- identifier helpers ----

// enumVariant strips the SCREAMING enum-name prefix (as prost-build does) and
// PascalCases the rest: (Action, ACTION_CREATE) -> Create.
func enumVariant(enum, value string) string {
	prefix := strings.ToUpper(strings.Join(splitWords(enum), "_")) + "_"
	rest := value
	if strings.HasPrefix(value, prefix) {
		rest = value[len(prefix):]
	}
	v := pascal(rest)
	if v == "" || !isLetter(rune(v[0])) {
		v = pascal(value) // stripping produced an invalid ident; keep the full name
	}
	return v
}

func pascal(s string) string {
	var out strings.Builder
	for _, w := range strings.Split(s, "_") {
		if w == "" {
			continue
		}
		r := []rune(strings.ToLower(w))
		r[0] = toUpper(r[0])
		out.WriteString(string(r))
	}
	return out.String()
}

// snake converts a Pascal/camel identifier to snake_case: GetBalance -> get_balance.
func snake(s string) string {
	words := splitWords(s)
	for i := range words {
		words[i] = strings.ToLower(words[i])
	}
	return strings.Join(words, "_")
}

// rustIdent keeps a snake_case proto field name, escaping Rust keywords.
func rustIdent(name string) string {
	switch name {
	// keywords that cannot be raw identifiers -> suffix instead
	case "crate", "self", "super", "Self":
		return name + "_"
	}
	if rustKeywords[name] {
		return "r#" + name
	}
	return name
}

var rustKeywords = map[string]bool{
	"as": true, "break": true, "const": true, "continue": true, "dyn": true,
	"else": true, "enum": true, "extern": true, "false": true, "fn": true,
	"for": true, "if": true, "impl": true, "in": true, "let": true, "loop": true,
	"match": true, "mod": true, "move": true, "mut": true, "pub": true, "ref": true,
	"return": true, "static": true, "struct": true, "trait": true, "true": true,
	"type": true, "unsafe": true, "use": true, "where": true, "while": true,
	"async": true, "await": true, "box": true, "final": true, "macro": true,
	"override": true, "priv": true, "try": true, "typeof": true, "union": true,
	"unsized": true, "virtual": true, "yield": true,
}

// splitWords splits a CamelCase / SCREAMING_SNAKE identifier into its words.
func splitWords(s string) []string {
	var words []string
	runes := []rune(s)
	start := 0
	for i := 1; i < len(runes); i++ {
		prev, cur := runes[i-1], runes[i]
		var next rune
		if i+1 < len(runes) {
			next = runes[i+1]
		}
		boundary := false
		switch {
		case isLower(prev) && isUpper(cur):
			boundary = true
		case isUpper(prev) && isUpper(cur) && isLower(next):
			boundary = true
		case (isLetter(prev) && isDigit(cur)) || (isDigit(prev) && isLetter(cur)):
			boundary = true
		case cur == '_':
			words = append(words, string(runes[start:i]))
			start = i + 1
			continue
		}
		if boundary {
			words = append(words, string(runes[start:i]))
			start = i
		}
	}
	if start < len(runes) {
		words = append(words, string(runes[start:]))
	}
	out := words[:0]
	for _, w := range words {
		if w != "" {
			out = append(out, w)
		}
	}
	return out
}

func toUpper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return r - 'a' + 'A'
	}
	return r
}
func isUpper(r rune) bool  { return r >= 'A' && r <= 'Z' }
func isLower(r rune) bool  { return r >= 'a' && r <= 'z' }
func isDigit(r rune) bool  { return r >= '0' && r <= '9' }
func isLetter(r rune) bool { return isUpper(r) || isLower(r) }
