// Code generated by dnatsgen. DO NOT EDIT.
// source: contract
#![allow(clippy::all, dead_code, unused_imports)]

use crate::dnats::{self, DnatsError};

// ==== messages ====

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, ::prost::Enumeration)]
#[repr(i32)]
pub enum Action {
    Unspecified = 0,
    Create = 1,
    Delete = 2,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBalanceRequest {
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub owner_id: ::prost::alloc::string::String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBalanceResponse {
    #[prost(string, tag = "1")]
    pub balance: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub currency_code: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub updated_at: i64,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferRequest {
    #[prost(string, tag = "1")]
    pub idempotency_key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub from_owner_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub to_owner_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub amount: ::prost::alloc::string::String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferResponse {
    #[prost(string, tag = "1")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub ok: bool,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PresenceChanged {
    #[prost(string, tag = "1")]
    pub player_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub server_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub ping_ms: i32,
    #[prost(string, repeated, tag = "4")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(sint32, tag = "5")]
    pub ping_delta: i32,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuditEntry {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(enumeration = "Action", tag = "3")]
    pub action: i32,
    #[prost(map = "string, string", tag = "4")]
    pub meta: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(int64, tag = "5")]
    pub at: i64,
    #[prost(sfixed64, tag = "6")]
    pub seq: i64,
}

// ==== NATS glue ====
use std::sync::Arc;

/// NATS subjects for this contract.
pub mod subjects {
    pub const WALLET_GET_BALANCE: &str = "wallet.get";
    pub const WALLET_TRANSFER: &str = "wallet.transfer";
    pub const PRESENCE_ONLINE: &str = "presence.online";
    pub const PRESENCE_OFFLINE: &str = "presence.offline";
    pub const AUDIT_LOGGED: &str = "audit.logged";
}

/// Generated NATS-RPC client for Wallet (async request/reply, protobuf wire).
#[derive(Clone)]
pub struct WalletClient {
    client: async_nats::Client,
}

impl WalletClient {
    pub fn new(client: async_nats::Client) -> Self {
        Self { client }
    }

    /// Calls `wallet.get`.
    pub async fn get_balance(&self, req: &GetBalanceRequest) -> Result<GetBalanceResponse, DnatsError> {
        dnats::request(&self.client, subjects::WALLET_GET_BALANCE, req, "type.googleapis.com/example.GetBalanceRequest").await
    }

    /// Calls `wallet.transfer`.
    pub async fn transfer(&self, req: &TransferRequest) -> Result<TransferResponse, DnatsError> {
        dnats::request(&self.client, subjects::WALLET_TRANSFER, req, "type.googleapis.com/example.TransferRequest").await
    }
}

/// Server-side contract for Wallet. Implement it, then call `serve_wallet`.
#[async_trait::async_trait]
pub trait WalletServer: Send + Sync + 'static {
    async fn get_balance(&self, req: GetBalanceRequest) -> Result<GetBalanceResponse, String>;
    async fn transfer(&self, req: TransferRequest) -> Result<TransferResponse, String>;
}

/// Subscribes `srv`'s handlers on the Wallet RPC subjects (spawns background tasks).
pub async fn serve_wallet<S: WalletServer>(
    client: async_nats::Client,
    srv: Arc<S>,
) -> Result<(), DnatsError> {
    use futures::StreamExt;
    {
        let mut sub = client.subscribe(subjects::WALLET_GET_BALANCE).await?;
        let client = client.clone();
        let srv = srv.clone();
        tokio::spawn(async move {
            while let Some(msg) = sub.next().await {
                let reply = match msg.reply {
                    Some(r) => r,
                    None => continue,
                };
                let payload = msg.payload;
                let client = client.clone();
                let srv = srv.clone();
                tokio::spawn(async move {
                    let result = match dnats::unwrap_value::<GetBalanceRequest>(&payload) {
                        Ok(req) => srv.get_balance(req).await,
                        Err(e) => Err(e.to_string()),
                    };
                    let _ = dnats::reply(&client, reply, result, "type.googleapis.com/example.GetBalanceResponse").await;
                });
            }
        });
    }
    {
        let mut sub = client.subscribe(subjects::WALLET_TRANSFER).await?;
        let client = client.clone();
        let srv = srv.clone();
        tokio::spawn(async move {
            while let Some(msg) = sub.next().await {
                let reply = match msg.reply {
                    Some(r) => r,
                    None => continue,
                };
                let payload = msg.payload;
                let client = client.clone();
                let srv = srv.clone();
                tokio::spawn(async move {
                    let result = match dnats::unwrap_value::<TransferRequest>(&payload) {
                        Ok(req) => srv.transfer(req).await,
                        Err(e) => Err(e.to_string()),
                    };
                    let _ = dnats::reply(&client, reply, result, "type.googleapis.com/example.TransferResponse").await;
                });
            }
        });
    }
    Ok(())
}

/// Publishes Presence events (core broadcast).
#[derive(Clone)]
pub struct PresencePublisher {
    client: async_nats::Client,
}

impl PresencePublisher {
    pub fn new(client: async_nats::Client) -> Self {
        Self { client }
    }

    /// Publishes `presence.online`.
    pub async fn online(&self, ev: &PresenceChanged) -> Result<(), DnatsError> {
        dnats::emit_core(&self.client, subjects::PRESENCE_ONLINE, ev, "type.googleapis.com/example.PresenceChanged").await
    }

    /// Publishes `presence.offline`.
    pub async fn offline(&self, ev: &PresenceChanged) -> Result<(), DnatsError> {
        dnats::emit_core(&self.client, subjects::PRESENCE_OFFLINE, ev, "type.googleapis.com/example.PresenceChanged").await
    }
}

/// Consumes Presence events. Implement it, then call `subscribe_presence`.
#[async_trait::async_trait]
pub trait PresenceHandler: Send + Sync + 'static {
    async fn online(&self, ev: PresenceChanged);
    async fn offline(&self, ev: PresenceChanged);
}

/// Subscribes `handler` on the Presence event subjects (spawns background tasks).
pub async fn subscribe_presence<H: PresenceHandler>(
    client: async_nats::Client,
    handler: Arc<H>,
) -> Result<(), DnatsError> {
    use futures::StreamExt;
    {
        let mut sub = client.subscribe(subjects::PRESENCE_ONLINE).await?;
        let handler = handler.clone();
        tokio::spawn(async move {
            while let Some(msg) = sub.next().await {
                if let Ok(ev) = dnats::unwrap_value::<PresenceChanged>(&msg.payload) {
                    handler.online(ev).await;
                }
            }
        });
    }
    {
        let mut sub = client.subscribe(subjects::PRESENCE_OFFLINE).await?;
        let handler = handler.clone();
        tokio::spawn(async move {
            while let Some(msg) = sub.next().await {
                if let Ok(ev) = dnats::unwrap_value::<PresenceChanged>(&msg.payload) {
                    handler.offline(ev).await;
                }
            }
        });
    }
    Ok(())
}

/// Publishes Audit events (JetStream stream AUDIT).
#[derive(Clone)]
pub struct AuditPublisher {
    js: async_nats::jetstream::Context,
}

impl AuditPublisher {
    pub fn new(js: async_nats::jetstream::Context) -> Self {
        Self { js }
    }

    /// Publishes `audit.logged`.
    pub async fn logged(&self, ev: &AuditEntry) -> Result<(), DnatsError> {
        dnats::emit_jetstream(&self.js, subjects::AUDIT_LOGGED, ev, "type.googleapis.com/example.AuditEntry").await
    }
}

/// Consumes Audit events. Implement it, then call `subscribe_audit`.
#[async_trait::async_trait]
pub trait AuditHandler: Send + Sync + 'static {
    async fn logged(&self, ev: AuditEntry);
}

/// Subscribes `handler` on the Audit event subjects (spawns background tasks).
pub async fn subscribe_audit<H: AuditHandler>(
    js: async_nats::jetstream::Context,
    handler: Arc<H>,
) -> Result<(), DnatsError> {
    use futures::StreamExt;
    {
        let mut messages = dnats::jetstream_messages(&js, "AUDIT", subjects::AUDIT_LOGGED).await?;
        let handler = handler.clone();
        tokio::spawn(async move {
            while let Some(Ok(msg)) = messages.next().await {
                if let Ok(ev) = dnats::unwrap_value::<AuditEntry>(&msg.payload) {
                    handler.logged(ev).await;
                }
                let _ = msg.ack().await;
            }
        });
    }
    Ok(())
}
