// Code generated by dnatsgen. DO NOT EDIT.
//
// `dnats` reproduces the deez-nats protobuf wire envelope
// (marshaller.ProtobufWrap { google.protobuf.Any data = 1; string error = 2; })
// on top of prost + async-nats, so Rust clients/servers are byte-compatible with
// Go services using marshaller.DefaultProtoMarshaller (and the Kotlin runtime).
#![allow(dead_code)]

use prost::Message;

/// google.protobuf.Any — { string type_url = 1; bytes value = 2; }.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Any {
    #[prost(string, tag = "1")]
    pub type_url: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}

/// deez-nats marshaller.ProtobufWrap — { Any data = 1; string error = 2; }.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtobufWrap {
    #[prost(message, optional, tag = "1")]
    pub data: ::core::option::Option<Any>,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}

/// Errors surfaced by the generated clients/servers.
#[derive(Debug)]
pub enum DnatsError {
    /// The remote handler responded with an error (envelope `error` field).
    Remote(String),
    /// A protobuf message failed to decode.
    Decode(prost::DecodeError),
    /// A NATS transport / JetStream operation failed.
    Nats(String),
}

impl std::fmt::Display for DnatsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DnatsError::Remote(e) => write!(f, "dnats remote error: {e}"),
            DnatsError::Decode(e) => write!(f, "dnats decode error: {e}"),
            DnatsError::Nats(e) => write!(f, "dnats nats error: {e}"),
        }
    }
}

impl std::error::Error for DnatsError {}

impl From<prost::DecodeError> for DnatsError {
    fn from(e: prost::DecodeError) -> Self {
        DnatsError::Decode(e)
    }
}

impl From<async_nats::SubscribeError> for DnatsError {
    fn from(e: async_nats::SubscribeError) -> Self {
        DnatsError::Nats(e.to_string())
    }
}

fn nats<E: std::fmt::Display>(e: E) -> DnatsError {
    DnatsError::Nats(e.to_string())
}

/// Packs `payload` into the deez-nats envelope (proto3, zero-values omitted).
pub fn wrap<T: Message>(payload: &T, type_url: &str) -> Vec<u8> {
    ProtobufWrap {
        data: Some(Any {
            type_url: type_url.to_string(),
            value: payload.encode_to_vec(),
        }),
        error: String::new(),
    }
    .encode_to_vec()
}

/// Unpacks an envelope: propagates a remote `error`, else decodes the `Any` value.
pub fn unwrap_value<T: Message + Default>(data: &[u8]) -> Result<T, DnatsError> {
    let w = ProtobufWrap::decode(data)?;
    if !w.error.is_empty() {
        return Err(DnatsError::Remote(w.error));
    }
    let value = w.data.map(|a| a.value).unwrap_or_default();
    Ok(T::decode(value.as_slice())?)
}

/// Blocking-style RPC: wraps `req`, waits for the reply, unwraps the response.
pub async fn request<Req: Message, Resp: Message + Default>(
    client: &async_nats::Client,
    subject: &str,
    req: &Req,
    type_url: &str,
) -> Result<Resp, DnatsError> {
    let msg = client
        .request(subject.to_string(), wrap(req, type_url).into())
        .await
        .map_err(nats)?;
    unwrap_value::<Resp>(&msg.payload)
}

/// Broadcasts a core-NATS event.
pub async fn emit_core<T: Message>(
    client: &async_nats::Client,
    subject: &str,
    ev: &T,
    type_url: &str,
) -> Result<(), DnatsError> {
    client
        .publish(subject.to_string(), wrap(ev, type_url).into())
        .await
        .map_err(nats)?;
    Ok(())
}

/// Publishes a JetStream event (awaits the publish ack).
pub async fn emit_jetstream<T: Message>(
    js: &async_nats::jetstream::Context,
    subject: &str,
    ev: &T,
    type_url: &str,
) -> Result<(), DnatsError> {
    js.publish(subject.to_string(), wrap(ev, type_url).into())
        .await
        .map_err(nats)?
        .await
        .map_err(nats)?;
    Ok(())
}

/// Server-side: replies to an RPC with a response or an error string.
pub async fn reply<Resp: Message>(
    client: &async_nats::Client,
    reply_to: async_nats::Subject,
    result: Result<Resp, String>,
    resp_type_url: &str,
) -> Result<(), DnatsError> {
    let payload = match result {
        Ok(resp) => wrap(&resp, resp_type_url),
        Err(e) => ProtobufWrap { data: None, error: e }.encode_to_vec(),
    };
    client.publish(reply_to, payload.into()).await.map_err(nats)?;
    Ok(())
}

/// Opens a JetStream pull-consumer message stream filtered to `subject`.
pub async fn jetstream_messages(
    js: &async_nats::jetstream::Context,
    stream: &str,
    subject: &str,
) -> Result<async_nats::jetstream::consumer::pull::Stream, DnatsError> {
    let stream = js.get_stream(stream.to_string()).await.map_err(nats)?;
    let consumer = stream
        .create_consumer(async_nats::jetstream::consumer::pull::Config {
            filter_subject: subject.to_string(),
            ..Default::default()
        })
        .await
        .map_err(nats)?;
    consumer.messages().await.map_err(nats)
}
