// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.0
// source: deeznats/annotations.proto

// Package deeznats holds the custom protobuf options that drive the deez-nats
// client/server code generator (dnatsgen). A contract .proto imports this file
// and annotates its services/methods with NATS subjects + transport intent.

package dnatsannotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_deeznats_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60001,
		Name:          "deeznats.subject_prefix",
		Tag:           "bytes,60001,opt,name=subject_prefix",
		Filename:      "deeznats/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         60002,
		Name:          "deeznats.events",
		Tag:           "varint,60002,opt,name=events",
		Filename:      "deeznats/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         60003,
		Name:          "deeznats.jetstream",
		Tag:           "varint,60003,opt,name=jetstream",
		Filename:      "deeznats/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60004,
		Name:          "deeznats.stream",
		Tag:           "bytes,60004,opt,name=stream",
		Filename:      "deeznats/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60001,
		Name:          "deeznats.subject",
		Tag:           "bytes,60001,opt,name=subject",
		Filename:      "deeznats/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         60002,
		Name:          "deeznats.event",
		Tag:           "varint,60002,opt,name=event",
		Filename:      "deeznats/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         60003,
		Name:          "deeznats.event_jetstream",
		Tag:           "varint,60003,opt,name=event_jetstream",
		Filename:      "deeznats/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60004,
		Name:          "deeznats.event_stream",
		Tag:           "bytes,60004,opt,name=event_stream",
		Filename:      "deeznats/annotations.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// subject_prefix is joined (with '.') in front of every method subject leaf,
	// e.g. "economy" -> "economy.wallet.get".
	//
	// optional string subject_prefix = 60001;
	E_SubjectPrefix = &file_deeznats_annotations_proto_extTypes[0]
	// events marks the whole service as pub/sub (fire-and-forget) instead of
	// request/reply RPC. Every method becomes an event.
	//
	// optional bool events = 60002;
	E_Events = &file_deeznats_annotations_proto_extTypes[1]
	// jetstream selects the events transport for this service:
	// true = JetStream (durable), false = core NATS (broadcast). Ignored for RPC.
	//
	// optional bool jetstream = 60003;
	E_Jetstream = &file_deeznats_annotations_proto_extTypes[2]
	// stream is the JetStream stream name used when jetstream = true.
	//
	// optional string stream = 60004;
	E_Stream = &file_deeznats_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// subject is the leaf appended to the service subject_prefix, e.g. "wallet.get".
	// When empty, dnatsgen derives it from the method name (GetBalance -> get.balance).
	//
	// optional string subject = 60001;
	E_Subject = &file_deeznats_annotations_proto_extTypes[4]
	// event marks a single method as an event inside an otherwise-RPC service.
	//
	// optional bool event = 60002;
	E_Event = &file_deeznats_annotations_proto_extTypes[5]
	// event_jetstream overrides the transport for this single event method.
	//
	// optional bool event_jetstream = 60003;
	E_EventJetstream = &file_deeznats_annotations_proto_extTypes[6]
	// event_stream overrides the JetStream stream for this single event method.
	//
	// optional string event_stream = 60004;
	E_EventStream = &file_deeznats_annotations_proto_extTypes[7]
)

var File_deeznats_annotations_proto protoreflect.FileDescriptor

const file_deeznats_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1adeeznats/annotations.proto\x12\bdeeznats\x1a google/protobuf/descriptor.proto:H\n" +
	"\x0esubject_prefix\x12\x1f.google.protobuf.ServiceOptions\x18\xe1\xd4\x03 \x01(\tR\rsubjectPrefix:9\n" +
	"\x06events\x12\x1f.google.protobuf.ServiceOptions\x18\xe2\xd4\x03 \x01(\bR\x06events:?\n" +
	"\tjetstream\x12\x1f.google.protobuf.ServiceOptions\x18\xe3\xd4\x03 \x01(\bR\tjetstream:9\n" +
	"\x06stream\x12\x1f.google.protobuf.ServiceOptions\x18\xe4\xd4\x03 \x01(\tR\x06stream::\n" +
	"\asubject\x12\x1e.google.protobuf.MethodOptions\x18\xe1\xd4\x03 \x01(\tR\asubject:6\n" +
	"\x05event\x12\x1e.google.protobuf.MethodOptions\x18\xe2\xd4\x03 \x01(\bR\x05event:I\n" +
	"\x0fevent_jetstream\x12\x1e.google.protobuf.MethodOptions\x18\xe3\xd4\x03 \x01(\bR\x0eeventJetstream:C\n" +
	"\fevent_stream\x12\x1e.google.protobuf.MethodOptions\x18\xe4\xd4\x03 \x01(\tR\veventStreamBDZBgithub.com/leinodev/deez-nats/dnatsgenannotations;dnatsannotationsb\x06proto3"

var file_deeznats_annotations_proto_goTypes = []any{
	(*descriptorpb.ServiceOptions)(nil), // 0: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 1: google.protobuf.MethodOptions
}
var file_deeznats_annotations_proto_depIdxs = []int32{
	0, // 0: deeznats.subject_prefix:extendee -> google.protobuf.ServiceOptions
	0, // 1: deeznats.events:extendee -> google.protobuf.ServiceOptions
	0, // 2: deeznats.jetstream:extendee -> google.protobuf.ServiceOptions
	0, // 3: deeznats.stream:extendee -> google.protobuf.ServiceOptions
	1, // 4: deeznats.subject:extendee -> google.protobuf.MethodOptions
	1, // 5: deeznats.event:extendee -> google.protobuf.MethodOptions
	1, // 6: deeznats.event_jetstream:extendee -> google.protobuf.MethodOptions
	1, // 7: deeznats.event_stream:extendee -> google.protobuf.MethodOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	0, // [0:8] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deeznats_annotations_proto_init() }
func file_deeznats_annotations_proto_init() {
	if File_deeznats_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deeznats_annotations_proto_rawDesc), len(file_deeznats_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 8,
			NumServices:   0,
		},
		GoTypes:           file_deeznats_annotations_proto_goTypes,
		DependencyIndexes: file_deeznats_annotations_proto_depIdxs,
		ExtensionInfos:    file_deeznats_annotations_proto_extTypes,
	}.Build()
	File_deeznats_annotations_proto = out.File
	file_deeznats_annotations_proto_goTypes = nil
	file_deeznats_annotations_proto_depIdxs = nil
}
