// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: protocol/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SomeStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnotherNumber int32                  `protobuf:"varint,1,opt,name=another_number,json=anotherNumber,proto3" json:"another_number,omitempty"`
	AnotherText   string                 `protobuf:"bytes,2,opt,name=another_text,json=anotherText,proto3" json:"another_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SomeStruct) Reset() {
	*x = SomeStruct{}
	mi := &file_protocol_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SomeStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomeStruct) ProtoMessage() {}

func (x *SomeStruct) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomeStruct.ProtoReflect.Descriptor instead.
func (*SomeStruct) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *SomeStruct) GetAnotherNumber() int32 {
	if x != nil {
		return x.AnotherNumber
	}
	return 0
}

func (x *SomeStruct) GetAnotherText() string {
	if x != nil {
		return x.AnotherText
	}
	return ""
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentTime      int64                  `protobuf:"varint,1,opt,name=sent_time,json=sentTime,proto3" json:"sent_time,omitempty"`
	Request       *SomeStruct            `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRequest) GetSentTime() int64 {
	if x != nil {
		return x.SentTime
	}
	return 0
}

func (x *HelloRequest) GetRequest() *SomeStruct {
	if x != nil {
		return x.Request
	}
	return nil
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentTime      int64                  `protobuf:"varint,1,opt,name=sent_time,json=sentTime,proto3" json:"sent_time,omitempty"`
	Response      *SomeStruct            `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResponse) GetSentTime() int64 {
	if x != nil {
		return x.SentTime
	}
	return 0
}

func (x *HelloResponse) GetResponse() *SomeStruct {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_protocol_protocol_proto protoreflect.FileDescriptor

const file_protocol_protocol_proto_rawDesc = "" +
	"\n" +
	"\x17protocol/protocol.proto\x12\bprotocol\"V\n" +
	"\n" +
	"SomeStruct\x12%\n" +
	"\x0eanother_number\x18\x01 \x01(\x05R\ranotherNumber\x12!\n" +
	"\fanother_text\x18\x02 \x01(\tR\vanotherText\"[\n" +
	"\fHelloRequest\x12\x1b\n" +
	"\tsent_time\x18\x01 \x01(\x03R\bsentTime\x12.\n" +
	"\arequest\x18\x02 \x01(\v2\x14.protocol.SomeStructR\arequest\"^\n" +
	"\rHelloResponse\x12\x1b\n" +
	"\tsent_time\x18\x01 \x01(\x03R\bsentTime\x120\n" +
	"\bresponse\x18\x02 \x01(\v2\x14.protocol.SomeStructR\bresponse2L\n" +
	"\vTestService\x12=\n" +
	"\n" +
	"TestMethod\x12\x16.protocol.HelloRequest\x1a\x17.protocol.HelloResponseB\rZ\v./;protocolb\x06proto3"

var (
	file_protocol_protocol_proto_rawDescOnce sync.Once
	file_protocol_protocol_proto_rawDescData []byte
)

func file_protocol_protocol_proto_rawDescGZIP() []byte {
	file_protocol_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_protocol_proto_rawDesc), len(file_protocol_protocol_proto_rawDesc)))
	})
	return file_protocol_protocol_proto_rawDescData
}

var file_protocol_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_protocol_proto_goTypes = []any{
	(*SomeStruct)(nil),    // 0: protocol.SomeStruct
	(*HelloRequest)(nil),  // 1: protocol.HelloRequest
	(*HelloResponse)(nil), // 2: protocol.HelloResponse
}
var file_protocol_protocol_proto_depIdxs = []int32{
	0, // 0: protocol.HelloRequest.request:type_name -> protocol.SomeStruct
	0, // 1: protocol.HelloResponse.response:type_name -> protocol.SomeStruct
	1, // 2: protocol.TestService.TestMethod:input_type -> protocol.HelloRequest
	2, // 3: protocol.TestService.TestMethod:output_type -> protocol.HelloResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_protocol_proto_init() }
func file_protocol_protocol_proto_init() {
	if File_protocol_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_protocol_proto_rawDesc), len(file_protocol_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_protocol_proto_msgTypes,
	}.Build()
	File_protocol_protocol_proto = out.File
	file_protocol_protocol_proto_goTypes = nil
	file_protocol_protocol_proto_depIdxs = nil
}
