// Package genkt emits the Kotlin side of a deez-nats contract: @Serializable
// message classes (encoded with kotlinx-serialization-protobuf, byte-compatible
// with Go's protobuf wire), subjects, typed clients, and event pub/sub helpers,
// plus a once-emitted DnatsProto runtime reproducing the deez-nats envelope.
package genkt

import (
	"bytes"
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/leinodev/deez-nats/dnatsgen/internal/model"
)

//go:embed templates/*.kt.tmpl
var templatesFS embed.FS

var (
	apiTmpl     = template.Must(template.New("Api.kt.tmpl").ParseFS(templatesFS, "templates/Api.kt.tmpl"))
	runtimeTmpl = template.Must(template.New("DnatsProto.kt.tmpl").ParseFS(templatesFS, "templates/DnatsProto.kt.tmpl"))
)

// GenerateContract emits Messages.kt and Api.kt for one contract into outDir.
func GenerateContract(fd protoreflect.FileDescriptor, c *model.Contract, runtimePackage, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "Messages.kt"), messagesFile(fd, c.KtPackage), 0o644); err != nil {
		return err
	}

	data := struct {
		Contract       *model.Contract
		RuntimePackage string
	}{Contract: c, RuntimePackage: runtimePackage}
	var buf bytes.Buffer
	if err := apiTmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("render Api.kt: %w", err)
	}
	return os.WriteFile(filepath.Join(outDir, "Api.kt"), buf.Bytes(), 0o644)
}

// GenerateRuntime emits DnatsProto.kt into outDir (emit once per Kotlin module).
func GenerateRuntime(runtimePackage, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := runtimeTmpl.Execute(&buf, struct{ RuntimePackage string }{runtimePackage}); err != nil {
		return fmt.Errorf("render DnatsProto.kt: %w", err)
	}
	return os.WriteFile(filepath.Join(outDir, "DnatsProto.kt"), buf.Bytes(), 0o644)
}

// messagesFile renders all @Serializable message classes + enums of a file.
func messagesFile(fd protoreflect.FileDescriptor, ktPackage string) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by dnatsgen. DO NOT EDIT.\n")
	b.WriteString("@file:OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)\n\n")
	fmt.Fprintf(&b, "package %s\n\n", ktPackage)
	b.WriteString("import kotlinx.serialization.Serializable\n")
	b.WriteString("import kotlinx.serialization.protobuf.ProtoNumber\n")
	b.WriteString("import kotlinx.serialization.protobuf.ProtoType\n")
	b.WriteString("import kotlinx.serialization.protobuf.ProtoIntegerType\n\n")

	var msgs []protoreflect.MessageDescriptor
	var enums []protoreflect.EnumDescriptor
	collect(fd.Messages(), fd.Enums(), &msgs, &enums)

	for _, ed := range enums {
		writeEnum(&b, ed)
	}
	for _, md := range msgs {
		writeMessage(&b, md)
	}
	return []byte(b.String())
}

// collect gathers all non-map-entry messages and enums, recursing into nested types.
func collect(msgs protoreflect.MessageDescriptors, enums protoreflect.EnumDescriptors, outMsgs *[]protoreflect.MessageDescriptor, outEnums *[]protoreflect.EnumDescriptor) {
	for i := 0; i < enums.Len(); i++ {
		*outEnums = append(*outEnums, enums.Get(i))
	}
	for i := 0; i < msgs.Len(); i++ {
		md := msgs.Get(i)
		if md.IsMapEntry() {
			continue
		}
		*outMsgs = append(*outMsgs, md)
		collect(md.Messages(), md.Enums(), outMsgs, outEnums)
	}
}

func writeEnum(b *strings.Builder, ed protoreflect.EnumDescriptor) {
	b.WriteString("@Serializable\n")
	fmt.Fprintf(b, "enum class %s {\n", ed.Name())
	vals := ed.Values()
	for i := 0; i < vals.Len(); i++ {
		v := vals.Get(i)
		fmt.Fprintf(b, "    @ProtoNumber(%d) %s,\n", v.Number(), v.Name())
	}
	b.WriteString("}\n\n")
}

func writeMessage(b *strings.Builder, md protoreflect.MessageDescriptor) {
	fields := md.Fields()
	b.WriteString("@Serializable\n")
	if fields.Len() == 0 {
		fmt.Fprintf(b, "class %s\n\n", md.Name())
		return
	}
	fmt.Fprintf(b, "data class %s(\n", md.Name())
	for i := 0; i < fields.Len(); i++ {
		fmt.Fprintf(b, "    %s,\n", ktField(fields.Get(i)))
	}
	b.WriteString(")\n\n")
}

// ktField renders one Kotlin constructor property for a proto field.
func ktField(fd protoreflect.FieldDescriptor) string {
	ann := fmt.Sprintf("@ProtoNumber(%d)", fd.Number())
	name := fd.JSONName()

	switch {
	case fd.IsMap():
		k := ktElemType(fd.MapKey())
		v := ktElemType(fd.MapValue())
		return fmt.Sprintf("%s val %s: Map<%s, %s> = emptyMap()", ann, name, k, v)
	case fd.IsList():
		if pt := ktProtoType(fd); pt != "" {
			ann += " " + pt
		}
		return fmt.Sprintf("%s val %s: List<%s> = emptyList()", ann, name, ktElemType(fd))
	}

	switch fd.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return fmt.Sprintf("%s val %s: %s? = null", ann, name, string(fd.Message().Name()))
	case protoreflect.EnumKind:
		en := string(fd.Enum().Name())
		def := string(fd.Enum().Values().ByNumber(0).Name())
		return fmt.Sprintf("%s val %s: %s = %s.%s", ann, name, en, en, def)
	default:
		if pt := ktProtoType(fd); pt != "" {
			ann += " " + pt
		}
		kt, def := ktScalar(fd.Kind())
		return fmt.Sprintf("%s val %s: %s = %s", ann, name, kt, def)
	}
}

// ktElemType is the Kotlin type of a repeated element / map key-or-value (no default).
func ktElemType(fd protoreflect.FieldDescriptor) string {
	switch fd.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return string(fd.Message().Name())
	case protoreflect.EnumKind:
		return string(fd.Enum().Name())
	default:
		kt, _ := ktScalar(fd.Kind())
		return kt
	}
}

// ktScalar maps a scalar proto kind to (Kotlin type, default literal).
func ktScalar(k protoreflect.Kind) (string, string) {
	switch k {
	case protoreflect.StringKind:
		return "String", `""`
	case protoreflect.BoolKind:
		return "Boolean", "false"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
		protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "Int", "0"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "Long", "0L"
	case protoreflect.FloatKind:
		return "Float", "0f"
	case protoreflect.DoubleKind:
		return "Double", "0.0"
	case protoreflect.BytesKind:
		return "ByteArray", "ByteArray(0)"
	default:
		return "String", `""`
	}
}

// ktProtoType returns the @ProtoType annotation for zigzag/fixed integer kinds.
func ktProtoType(fd protoreflect.FieldDescriptor) string {
	switch fd.Kind() {
	case protoreflect.Sint32Kind, protoreflect.Sint64Kind:
		return "@ProtoType(ProtoIntegerType.SIGNED)"
	case protoreflect.Fixed32Kind, protoreflect.Fixed64Kind,
		protoreflect.Sfixed32Kind, protoreflect.Sfixed64Kind:
		return "@ProtoType(ProtoIntegerType.FIXED)"
	default:
		return ""
	}
}
