// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: protocol/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cipher        string                 `protobuf:"bytes,2,opt,name=cipher,proto3" json:"cipher,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	TcpMaxConn    uint32                 `protobuf:"varint,6,opt,name=tcp_max_conn,json=tcpMaxConn,proto3" json:"tcp_max_conn,omitempty"`
	UdpTimeoutMs  int32                  `protobuf:"varint,7,opt,name=udp_timeout_ms,json=udpTimeoutMs,proto3" json:"udp_timeout_ms,omitempty"`
	UdpBufferSize int32                  `protobuf:"varint,8,opt,name=udp_buffer_size,json=udpBufferSize,proto3" json:"udp_buffer_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProxyRequest) Reset() {
	*x = StartProxyRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProxyRequest) ProtoMessage() {}

func (x *StartProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProxyRequest.ProtoReflect.Descriptor instead.
func (*StartProxyRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *StartProxyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartProxyRequest) GetCipher() string {
	if x != nil {
		return x.Cipher
	}
	return ""
}

func (x *StartProxyRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StartProxyRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *StartProxyRequest) GetTcpMaxConn() uint32 {
	if x != nil {
		return x.TcpMaxConn
	}
	return 0
}

func (x *StartProxyRequest) GetUdpTimeoutMs() int32 {
	if x != nil {
		return x.UdpTimeoutMs
	}
	return 0
}

func (x *StartProxyRequest) GetUdpBufferSize() int32 {
	if x != nil {
		return x.UdpBufferSize
	}
	return 0
}

type StartProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProxyResponse) Reset() {
	*x = StartProxyResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProxyResponse) ProtoMessage() {}

func (x *StartProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProxyResponse.ProtoReflect.Descriptor instead.
func (*StartProxyResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *StartProxyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartProxyResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StartProxyResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ProxyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyInfo) Reset() {
	*x = ProxyInfo{}
	mi := &file_protocol_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyInfo) ProtoMessage() {}

func (x *ProxyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyInfo.ProtoReflect.Descriptor instead.
func (*ProxyInfo) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProxyInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProxyInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ProxyInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ListProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProxyRequest) Reset() {
	*x = ListProxyRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProxyRequest) ProtoMessage() {}

func (x *ListProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProxyRequest.ProtoReflect.Descriptor instead.
func (*ListProxyRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{3}
}

type ListProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proxies       []*ProxyInfo           `protobuf:"bytes,1,rep,name=proxies,proto3" json:"proxies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProxyResponse) Reset() {
	*x = ListProxyResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProxyResponse) ProtoMessage() {}

func (x *ListProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProxyResponse.ProtoReflect.Descriptor instead.
func (*ListProxyResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *ListProxyResponse) GetProxies() []*ProxyInfo {
	if x != nil {
		return x.Proxies
	}
	return nil
}

type StopProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProxyRequest) Reset() {
	*x = StopProxyRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProxyRequest) ProtoMessage() {}

func (x *StopProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProxyRequest.ProtoReflect.Descriptor instead.
func (*StopProxyRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *StopProxyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProxyResponse) Reset() {
	*x = StopProxyResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProxyResponse) ProtoMessage() {}

func (x *StopProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProxyResponse.ProtoReflect.Descriptor instead.
func (*StopProxyResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *StopProxyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StopProxyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protocol_protocol_proto protoreflect.FileDescriptor

const file_protocol_protocol_proto_rawDesc = "" +
	"\n" +
	"\x17protocol/protocol.proto\x12\bprotocol\"\xe2\x01\n" +
	"\x11StartProxyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06cipher\x18\x02 \x01(\tR\x06cipher\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x12 \n" +
	"\ftcp_max_conn\x18\x06 \x01(\rR\n" +
	"tcpMaxConn\x12$\n" +
	"\x0eudp_timeout_ms\x18\a \x01(\x05R\fudpTimeoutMs\x12&\n" +
	"\x0fudp_buffer_size\x18\b \x01(\x05R\rudpBufferSize\"T\n" +
	"\x12StartProxyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"c\n" +
	"\tProxyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"\x12\n" +
	"\x10ListProxyRequest\"B\n" +
	"\x11ListProxyResponse\x12-\n" +
	"\aproxies\x18\x01 \x03(\v2\x13.protocol.ProxyInfoR\aproxies\"\"\n" +
	"\x10StopProxyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x11StopProxyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB\rZ\v./;protocolb\x06proto3"

var (
	file_protocol_protocol_proto_rawDescOnce sync.Once
	file_protocol_protocol_proto_rawDescData []byte
)

func file_protocol_protocol_proto_rawDescGZIP() []byte {
	file_protocol_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_protocol_proto_rawDesc), len(file_protocol_protocol_proto_rawDesc)))
	})
	return file_protocol_protocol_proto_rawDescData
}

var file_protocol_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protocol_protocol_proto_goTypes = []any{
	(*StartProxyRequest)(nil),  // 0: protocol.StartProxyRequest
	(*StartProxyResponse)(nil), // 1: protocol.StartProxyResponse
	(*ProxyInfo)(nil),          // 2: protocol.ProxyInfo
	(*ListProxyRequest)(nil),   // 3: protocol.ListProxyRequest
	(*ListProxyResponse)(nil),  // 4: protocol.ListProxyResponse
	(*StopProxyRequest)(nil),   // 5: protocol.StopProxyRequest
	(*StopProxyResponse)(nil),  // 6: protocol.StopProxyResponse
}
var file_protocol_protocol_proto_depIdxs = []int32{
	2, // 0: protocol.ListProxyResponse.proxies:type_name -> protocol.ProxyInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protocol_protocol_proto_init() }
func file_protocol_protocol_proto_init() {
	if File_protocol_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_protocol_proto_rawDesc), len(file_protocol_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_protocol_proto_msgTypes,
	}.Build()
	File_protocol_protocol_proto = out.File
	file_protocol_protocol_proto_goTypes = nil
	file_protocol_protocol_proto_depIdxs = nil
}
