// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: marshaller/protocol.proto

package marshaller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtobufWrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *anypb.Any             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtobufWrap) Reset() {
	*x = ProtobufWrap{}
	mi := &file_marshaller_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtobufWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtobufWrap) ProtoMessage() {}

func (x *ProtobufWrap) ProtoReflect() protoreflect.Message {
	mi := &file_marshaller_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtobufWrap.ProtoReflect.Descriptor instead.
func (*ProtobufWrap) Descriptor() ([]byte, []int) {
	return file_marshaller_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ProtobufWrap) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProtobufWrap) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProtobufTestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtobufTestMessage) Reset() {
	*x = ProtobufTestMessage{}
	mi := &file_marshaller_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtobufTestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtobufTestMessage) ProtoMessage() {}

func (x *ProtobufTestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_marshaller_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtobufTestMessage.ProtoReflect.Descriptor instead.
func (*ProtobufTestMessage) Descriptor() ([]byte, []int) {
	return file_marshaller_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ProtobufTestMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtobufTestMessage) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_marshaller_protocol_proto protoreflect.FileDescriptor

const file_marshaller_protocol_proto_rawDesc = "" +
	"\n" +
	"\x19marshaller/protocol.proto\x12\n" +
	"marshaller\x1a\x19google/protobuf/any.proto\"N\n" +
	"\fProtobufWrap\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa1\x01\n" +
	"\x13ProtobufTestMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\x04data\x18\x02 \x03(\v2).marshaller.ProtobufTestMessage.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0fZ\r./;marshallerb\x06proto3"

var (
	file_marshaller_protocol_proto_rawDescOnce sync.Once
	file_marshaller_protocol_proto_rawDescData []byte
)

func file_marshaller_protocol_proto_rawDescGZIP() []byte {
	file_marshaller_protocol_proto_rawDescOnce.Do(func() {
		file_marshaller_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marshaller_protocol_proto_rawDesc), len(file_marshaller_protocol_proto_rawDesc)))
	})
	return file_marshaller_protocol_proto_rawDescData
}

var file_marshaller_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_marshaller_protocol_proto_goTypes = []any{
	(*ProtobufWrap)(nil),        // 0: marshaller.ProtobufWrap
	(*ProtobufTestMessage)(nil), // 1: marshaller.ProtobufTestMessage
	nil,                         // 2: marshaller.ProtobufTestMessage.DataEntry
	(*anypb.Any)(nil),           // 3: google.protobuf.Any
}
var file_marshaller_protocol_proto_depIdxs = []int32{
	3, // 0: marshaller.ProtobufWrap.data:type_name -> google.protobuf.Any
	2, // 1: marshaller.ProtobufTestMessage.data:type_name -> marshaller.ProtobufTestMessage.DataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_marshaller_protocol_proto_init() }
func file_marshaller_protocol_proto_init() {
	if File_marshaller_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marshaller_protocol_proto_rawDesc), len(file_marshaller_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marshaller_protocol_proto_goTypes,
		DependencyIndexes: file_marshaller_protocol_proto_depIdxs,
		MessageInfos:      file_marshaller_protocol_proto_msgTypes,
	}.Build()
	File_marshaller_protocol_proto = out.File
	file_marshaller_protocol_proto_goTypes = nil
	file_marshaller_protocol_proto_depIdxs = nil
}
