// Code generated by dnatsgen. DO NOT EDIT.
package ru.lnik801l.example

import io.nats.client.Connection
import io.nats.client.Dispatcher
import io.nats.client.JetStream
import io.nats.client.JetStreamSubscription
import ru.lnik801l.example.runtime.DnatsProto

/** NATS subjects for this contract. */
object Subjects {
    const val WALLET_GET_BALANCE = "wallet.get"
    const val WALLET_TRANSFER = "wallet.transfer"
    const val PRESENCE_ONLINE = "presence.online"
    const val PRESENCE_OFFLINE = "presence.offline"
    const val AUDIT_LOGGED = "audit.logged"
}

/** Generated NATS-RPC client for Wallet (blocking request/reply, protobuf wire). */
class WalletClient(private val conn: Connection, private val timeoutMs: Long = 5_000) {
    fun getBalance(req: GetBalanceRequest): GetBalanceResponse =
        DnatsProto.request(conn, Subjects.WALLET_GET_BALANCE, req, GetBalanceRequest.serializer(),
            "type.googleapis.com/example.GetBalanceRequest", GetBalanceResponse.serializer(), timeoutMs)
    fun transfer(req: TransferRequest): TransferResponse =
        DnatsProto.request(conn, Subjects.WALLET_TRANSFER, req, TransferRequest.serializer(),
            "type.googleapis.com/example.TransferRequest", TransferResponse.serializer(), timeoutMs)
}

/** Publishes Presence events (core broadcast). */
class PresencePublisher(private val conn: Connection) {
    fun online(ev: PresenceChanged) =
        DnatsProto.emitCore(conn, Subjects.PRESENCE_ONLINE, ev, PresenceChanged.serializer(), "type.googleapis.com/example.PresenceChanged")
    fun offline(ev: PresenceChanged) =
        DnatsProto.emitCore(conn, Subjects.PRESENCE_OFFLINE, ev, PresenceChanged.serializer(), "type.googleapis.com/example.PresenceChanged")
}

/** Subscribes to Presence events. */
object PresenceSubscriber {
    fun online(conn: Connection, handler: (PresenceChanged) -> Unit): Dispatcher =
        DnatsProto.subscribeCore(conn, Subjects.PRESENCE_ONLINE, PresenceChanged.serializer(), handler)
    fun offline(conn: Connection, handler: (PresenceChanged) -> Unit): Dispatcher =
        DnatsProto.subscribeCore(conn, Subjects.PRESENCE_OFFLINE, PresenceChanged.serializer(), handler)
}

/** Publishes Audit events (JetStream stream AUDIT). */
class AuditPublisher(private val js: JetStream) {
    fun logged(ev: AuditEntry) =
        DnatsProto.emitJetStream(js, Subjects.AUDIT_LOGGED, ev, AuditEntry.serializer(), "type.googleapis.com/example.AuditEntry")
}

/** Subscribes to Audit events. */
object AuditSubscriber {
    fun logged(js: JetStream, dispatcher: Dispatcher, handler: (AuditEntry) -> Unit): JetStreamSubscription =
        DnatsProto.subscribeJetStream(js, dispatcher, Subjects.AUDIT_LOGGED, AuditEntry.serializer(), handler)
}

