// Code generated by dnatsgen. DO NOT EDIT.
@file:OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)

package ru.lnik801l.example

import kotlinx.serialization.Serializable
import kotlinx.serialization.protobuf.ProtoNumber
import kotlinx.serialization.protobuf.ProtoType
import kotlinx.serialization.protobuf.ProtoIntegerType

@Serializable
enum class Action {
    @ProtoNumber(0) ACTION_UNSPECIFIED,
    @ProtoNumber(1) ACTION_CREATE,
    @ProtoNumber(2) ACTION_DELETE,
}

@Serializable
data class GetBalanceRequest(
    @ProtoNumber(1) val serverId: String = "",
    @ProtoNumber(2) val ownerId: String = "",
)

@Serializable
data class GetBalanceResponse(
    @ProtoNumber(1) val balance: String = "",
    @ProtoNumber(2) val currencyCode: String = "",
    @ProtoNumber(3) val updatedAt: Long = 0L,
)

@Serializable
data class TransferRequest(
    @ProtoNumber(1) val idempotencyKey: String = "",
    @ProtoNumber(2) val fromOwnerId: String = "",
    @ProtoNumber(3) val toOwnerId: String = "",
    @ProtoNumber(4) val amount: String = "",
)

@Serializable
data class TransferResponse(
    @ProtoNumber(1) val transactionId: String = "",
    @ProtoNumber(2) val ok: Boolean = false,
)

@Serializable
data class PresenceChanged(
    @ProtoNumber(1) val playerId: String = "",
    @ProtoNumber(2) val serverId: String = "",
    @ProtoNumber(3) val pingMs: Int = 0,
    @ProtoNumber(4) val roles: List<String> = emptyList(),
    @ProtoNumber(5) @ProtoType(ProtoIntegerType.SIGNED) val pingDelta: Int = 0,
)

@Serializable
data class AuditEntry(
    @ProtoNumber(1) val id: String = "",
    @ProtoNumber(2) val actorId: String = "",
    @ProtoNumber(3) val action: Action = Action.ACTION_UNSPECIFIED,
    @ProtoNumber(4) val meta: Map<String, String> = emptyMap(),
    @ProtoNumber(5) val at: Long = 0L,
    @ProtoNumber(6) @ProtoType(ProtoIntegerType.FIXED) val seq: Long = 0L,
)

